name: build_cmake
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4320  # 72 hours
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
            submodules: 'true'

      - name: build
        timeout-minutes: 4320  # 72 hours
        run: |
          echo "Building the project..."
          docker build ./ytsaurus -f ./Dockerfile
